name: Compile and Release Murad's Sudo

on:
  push:
    tags:
      - 'v1.0.0'

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4

    - name: Compile C Code
      run: gcc msudo.c -o msudo.exe

    - name: Create Permanent Release
      uses: softprops/action-gh-release@v2
      with:
        files: msudo.exe
